//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_Hotel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Racun
    {
        [Display(Name = "Broj računa")]
        public int RacunID { get; set; }

        [Display(Name = "Broj rezervacije")]
        public int RezervacijaID { get; set; }

        [Display(Name = "Način plaćanja")]
        [Required(ErrorMessage = "Molimo, odaberite nacin placanja")]
        public string NacinPlacanja { get; set; }

        public Nullable<double> Iznos { get; set; }

        public string Storno { get; set; }

        public virtual Rezervacija Rezervacija { get; set; }
    }
}
