//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        public int RacunID { get; set; }
        public int RezervacijaID { get; set; }
        public string NacinPlacanja { get; set; }
        public Nullable<double> Iznos { get; set; }
    
        public virtual Rezervacija Rezervacija { get; set; }
    }
}
