//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervacija()
        {
            this.Racuns = new HashSet<Racun>();
        }
    
        public int RezervacijaID { get; set; }
        public int GostID { get; set; }
        public int UslugaID { get; set; }
        public System.DateTime Check_In { get; set; }
        public System.DateTime Check_Out { get; set; }
        public int SobaID { get; set; }
    
        public virtual Gost Gost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Racun> Racuns { get; set; }
        public virtual Soba Soba { get; set; }
        public virtual Usluga Usluga { get; set; }
    }
}
