//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Soba()
        {
            this.Rezervacijas = new HashSet<Rezervacija>();
        }
    
        public int SobaID { get; set; }
        public int BrojKreveta { get; set; }
        public string Pogled { get; set; }
        public int Sprat { get; set; }
        public int StatusID { get; set; }
        public double Cena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacijas { get; set; }
        public virtual StatusSobe StatusSobe { get; set; }
    }
}
